print("Programa para calcular la nota final de un estudiante")
n1=float(input("Introduzca la primera nota: "))
n2=float(input("Introduzca la segunda nota: "))
n3=float(input("Introduzca la tercer nota: "))
n4=float(input("Introduzca la cuarta nota: "))
n5=float(input("Introduzca la quinta nota: "))
nota1=(n1*0.15)
nota2=(n2*0.20)
nota3=(n3*0.15)
nota4=(n4*0.30)
nota5=(n5*0.20)
n_final=(nota1+nota2+nota3+nota4+nota5)
print("Su nota final es: "+ n_final)
