print("Programa para calcular el promedio de tres números")
num1=int(input("Ingrese el primer número: "))
num2=int(input("Ingrese el segundo número: "))
num3=int(input("Ingrese el tercer número: "))
prom=int((num1+num2+num3)/3)
print("El promedio de los números es: ", prom)
